import type { Project, RewardTier, FundingUpdate } from "@/types";

export const MOCK_PROJECTS: Project[] = [
  {
    id: "1",
    title: "Монгол AI Туслагч — Ухаалаг чатбот",
    slug: "mongol-ai-assistant",
    description:
      "Монгол хэл дээр бүрэн ажилладаг анхны AI туслагч. Монголчуудын өдөр тутмын асуудлыг шийдэх зориулалттай.",
    category: "technology",
    coverImage: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80",
    creator: {
      id: "c1",
      name: "Б. Тэгшжаргал",
      avatar: "https://i.pravatar.cc/48?img=11",
      isVerified: true,
      projectCount: 3,
    },
    goal: 50_000_000,
    raised: 38_200_000,
    backers: 412,
    daysLeft: 14,
    isVerified: true,
    isTrending: true,
    tags: ["AI", "Монгол хэл", "технологи"],
  },
  {
    id: "2",
    title: "Говийн дэлхийн нарны эрчим хүч төсөл",
    slug: "gobi-solar-energy",
    description:
      "Говийн 10 сумын айл өрхийг нарны эрчим хүчээр тасралтгүй хангах, байгаль орчинд ээлтэй шийдэл.",
    category: "environment",           // was "social"
    coverImage: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&q=80",
    creator: {
      id: "c2",
      name: "Н. Оюунбаатар",
      avatar: "https://i.pravatar.cc/48?img=22",
      isVerified: true,
      projectCount: 1,
    },
    goal: 120_000_000,
    raised: 89_500_000,
    backers: 1203,
    daysLeft: 8,
    isVerified: true,
    isTrending: true,
    tags: ["нарны эрчим хүч", "байгаль орчин", "ногоон эрчим хүч"],
  },
  {
    id: "3",
    title: "Монгол дизайны цуглуулга — Уламжлал × Орчин үе",
    slug: "mongol-design-collection",
    description:
      "Монгол угалзны загвар орчин үеийн фэшнтэй хослуулсан дизайн цуглуулга. Монгол соёлыг дэлхийд таниулах зорилготой.",
    category: "fashion",               // was "arts" — fits fashion better
    coverImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    creator: {
      id: "c3",
      name: "Х. Мөнхзул",
      avatar: "https://i.pravatar.cc/48?img=33",
      isVerified: false,
      projectCount: 2,
    },
    goal: 15_000_000,
    raised: 16_800_000,
    backers: 287,
    daysLeft: 5,
    isVerified: false,
    isTrending: false,
    tags: ["дизайн", "загвар", "фэшн", "монгол соёл"],
  },
  {
    id: "4",
    title: "Хөдөөгийн сурагчдын онлайн боловсрол",
    slug: "rural-online-education",
    description:
      "Интернет хүрэхгүй хөдөөгийн 5000+ сурагчид чанартай боловсрол авах боломжийг бүрдүүлэх.",
    category: "education",
    coverImage: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80",
    creator: {
      id: "c4",
      name: "Д. Энхбаяр",
      avatar: "https://i.pravatar.cc/48?img=44",
      isVerified: true,
      projectCount: 4,
    },
    goal: 30_000_000,
    raised: 22_400_000,
    backers: 634,
    daysLeft: 21,
    isVerified: true,
    isTrending: false,
    tags: ["боловсрол", "хөдөө", "онлайн"],
  },
  {
    id: "5",
    title: "Эко-Гэр: Орчин үеийн тогтвортой гэр",
    slug: "eco-ger-sustainable",
    description:
      "Уламжлалт монгол гэрийн загварт тулгуурлан орчин үеийн тогтвортой материалаар хийгдсэн цаг уурын өөрчлөлтөд тэсвэртэй гэр.",
    category: "community",             // was "startups"
    coverImage: "https://images.unsplash.com/photo-1518623489648-a173ef7824f3?w=800&q=80",
    creator: {
      id: "c5",
      name: "С. Батболд",
      avatar: "https://i.pravatar.cc/48?img=55",
      isVerified: true,
      projectCount: 1,
    },
    goal: 80_000_000,
    raised: 31_000_000,
    backers: 189,
    daysLeft: 30,
    isVerified: true,
    isFeatured: true,
    tags: ["нийгэм", "тогтвортой байдал", "гэр", "орон сууц"],
  },
  {
    id: "6",
    title: "Монголын эмэгтэйчүүдийн эрүүл мэндийн апп",
    slug: "mongolian-womens-health-app",
    description:
      "Эмэгтэйчүүдэд зориулсан монгол хэл дээрх эрүүл мэндийн мэдээлэл, эмчтэй холбогдох, эм жор авах боломжтой апп.",
    category: "health",
    coverImage: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&q=80",
    creator: {
      id: "c6",
      name: "Э. Наранцэцэг",
      avatar: "https://i.pravatar.cc/48?img=66",
      isVerified: true,
      projectCount: 2,
    },
    goal: 25_000_000,
    raised: 19_750_000,
    backers: 891,
    daysLeft: 12,
    isVerified: true,
    isTrending: true,
    tags: ["эрүүл мэнд", "эмэгтэй", "апп"],
  },
  {
    id: "7",
    title: "Говийн байгаль хамгаалалын санаачлага",
    slug: "gobi-nature-conservation",
    description:
      "Говийн цөлийн өвөрмөц экосистемийг хамгаалах, нутгийн иргэдийн амьжиргааг дэмжих нийгмийн санаачлага.",
    category: "environment",           // was "social"
    coverImage: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
    creator: {
      id: "c7",
      name: "Г. Дорждагва",
      avatar: "https://i.pravatar.cc/48?img=7",
      isVerified: true,
      projectCount: 2,
    },
    goal: 65_000_000,
    raised: 41_200_000,
    backers: 834,
    daysLeft: 18,
    isVerified: true,
    isTrending: false,
    tags: ["байгаль орчин", "говь", "хамгаалал"],
  },
  {
    id: "8",
    title: "Монгол хоолны дижитал рецептийн ном",
    slug: "mongolian-food-digital-cookbook",
    description:
      "Монгол уламжлалт хоол хийх арга барилыг дижитал хэлбэрт оруулах, залуу үеийнхэнд соёлоо дамжуулах боловсролын төсөл.",
    category: "food",                  // was "education"
    coverImage: "https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=800&q=80",
    creator: {
      id: "c8",
      name: "Б. Цэцэгмаа",
      avatar: "https://i.pravatar.cc/48?img=47",
      isVerified: true,
      projectCount: 1,
    },
    goal: 18_000_000,
    raised: 15_900_000,
    backers: 1047,
    daysLeft: 4,
    isVerified: true,
    isTrending: true,
    tags: ["хоол", "рецепт", "монгол соёл", "дижитал"],
  },
  {
    id: "9",

    title: "Нүүдэлчдийн ардын дуу хөгжмийн архив",
    slug: "nomad-folk-music-archive",
    description:
      "Монголын нүүдэлчдийн уламжлалт дуу хөгжмийг дижитал архивлах, ирээдүй үедэд хадгалж үлдээх урлагийн төсөл.",
    category: "music",                 // was "arts"
    coverImage: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80",
    creator: {
      id: "c9",
      name: "Ц. Мөнхбаяр",
      avatar: "https://i.pravatar.cc/48?img=59",
      isVerified: false,
      projectCount: 3,
    },
    goal: 22_000_000,
    raised: 7_500_000,
    backers: 298,
    daysLeft: 38,
    isVerified: false,
    isTrending: false,
    tags: ["хөгжим", "уламжлал", "архив", "соёл"],
  },
];

export const MOCK_REWARD_TIERS: Record<string, RewardTier[]> = {
  "mongol-ai-assistant": [
    {
      id: "t1",
      title: "Дэмжигч",
      amount: 10_000,
      description: "Манай байгууллагын хөгжүүлэлтийг дэмжигч болно. Апп гарахад хамгийн түрүүнд мэдэгдэл хүлээн авна.",
      backerCount: 287,
      estimatedDelivery: "2025-08",
      isLimited: false,
    },
    {
      id: "t2",
      title: "Бета хэрэглэгч",
      amount: 50_000,
      description: "Апп гарахаас өмнө бета хувилбарт хандах эрх. Буцаах хүсэлтийн тэргүүлэх дэмжлэг. Тусгай шинж чанарт хандах боломж.",
      backerCount: 94,
      estimatedDelivery: "2025-07",
      isLimited: true,
      remaining: 6,
    },
    {
      id: "t3",
      title: "Platinum гишүүн",
      amount: 150_000,
      description: "1 жилийн premium хандалт + нэрийн жагсаалтад орно + хөгжүүлэгчидтэй шууд холбоо барих боломж. Онцгой шинж чанарт эрт хандах эрх.",
      backerCount: 31,
      estimatedDelivery: "2025-07",
      isLimited: true,
      remaining: 19,
    },
  ],
  "gobi-solar-energy": [
    {
      id: "gs1",
      title: "Байгаль хамгаалагч",
      amount: 25_000,
      description: "Говийн нарны эрчим хүчийн төслийг дэмжигч болно. Тайлан, шинэчлэлт хүлээн авна.",
      backerCount: 412,
      estimatedDelivery: "2025-09",
      isLimited: false,
    },
    {
      id: "gs2",
      title: "Ногоон санхүүжигч",
      amount: 100_000,
      description: "Баталгааны гэрчилгээ + дижитал хүрэл тэмдэг + жилийн тайлан.",
      backerCount: 203,
      estimatedDelivery: "2025-09",
      isLimited: false,
    },
    {
      id: "gs3",
      title: "Нарны аав/ээж",
      amount: 500_000,
      description: "Нэг айл өрхийг нарны эрчим хүчээр хангах зардлыг бүрэн санхүүжүүлнэ. Тухайн өрхийн гэр дээр таны нэр бичигдэнэ.",
      backerCount: 12,
      estimatedDelivery: "2025-12",
      isLimited: true,
      remaining: 8,
    },
  ],
  "rural-online-education": [
    {
      id: "re1",
      title: "Боловсрол дэмжигч",
      amount: 15_000,
      description: "Нэг сурагчийн нэг улирлын онлайн боловсролын зардлыг дэмжинэ.",
      backerCount: 318,
      estimatedDelivery: "2025-09",
      isLimited: false,
    },
    {
      id: "re2",
      title: "Ангийн ивээн тэтгэгч",
      amount: 75_000,
      description: "Нэг анги (30 сурагч)-ын нэг улирлын хичээлийн зардлыг дэмжинэ. Баярын захидал + сурагчдын зураг.",
      backerCount: 89,
      estimatedDelivery: "2025-09",
      isLimited: false,
    },
  ],
};

export const MOCK_UPDATES: Record<string, FundingUpdate[]> = {
  "mongol-ai-assistant": [
    {
      id: "u1",
      title: "Анхны 100 дэмжигчдэд баярлалаа!",
      content: "Хамгийн анхны 100 дэмжигчдэддээ гүнээ баярлалаа. Таны дэмжлэг манай багт маш их урам зориг өглөө. Бета тест 2025 оны 7-р сарын эхний долоо хоногт эхлэх болно. Бүх бета хэрэглэгчид цахим шуудангаар мэдэгдэл хүлээн авна.",
      createdAt: "2025-01-15",
      projectId: "1",
    },
    {
      id: "u2",
      title: "Монгол хэлний загвар сургалт амжилттай дууслаа",
      content: "Манай AI загварын монгол хэлний сургалт амжилттай дууслаа. Туршилтын үед 94.2% нарийвчлалтай байгааг баталгаажууллаа. Одоо хэрэглэгчийн интерфэйс хөгжүүлэх шатанд орж байна. Дараагийн шинэчлэлтэнд бид Beta 0.1 хувилбарын тухай мэдэгдэнэ.",
      createdAt: "2025-02-03",
      projectId: "1",
    },
  ],
  "gobi-solar-energy": [
    {
      id: "gu1",
      title: "Говийн талбайн судалгаа дууслаа",
      content: "Нарны эрчим хүчний төхөөрөмж байршуулах оновчтой газруудыг тодорхойллоо. 3 суманд нийт 150 гаруй айл өрхийг хамруулах боломжтой гэдгийг тогтооллоо.",
      createdAt: "2025-01-20",
      projectId: "2",
    },
  ],
  "rural-online-education": [
    {
      id: "eu1",
      title: "Пилот хөтөлбөр Хөвсгөлд эхэллээ",
      content: "Хөвсгөл аймгийн Мөрөн суманд анхны пилот хөтөлбөрийг эхлүүллээ. 120 сурагч онлайн хичээлд хамрагдаж эхлэв. Багш нарын сургалт амжилттай боллоо.",
      createdAt: "2025-01-28",
      projectId: "4",
    },
    {
      id: "eu2",
      title: "500+ сурагч хамрагдлаа",
      content: "Нэг сарын дотор 500 гаруй сурагч манай платформд бүртгэгдлээ. Энэ нь зорилтот тооноос 2 дахин их юм. Цаашид Архангай, Завхан аймгийг хамруулах төлөвлөгөөтэй байна.",
      createdAt: "2025-02-10",
      projectId: "4",
    },
  ],
};
